package eu.ubitech.broker.hibernate.models;
// Generated Jun 16, 2014 4:29:36 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchaseOrder generated by hbm2java
 */
@Entity
@Table(name="purchase_order"
    ,catalog="broker"
)
public class PurchaseOrder  implements java.io.Serializable {


     private int orderNum;
     private Product product;
     private Customer customer;
     private Short quantity;
     private BigDecimal shippingCost;
     private Date salesDate;
     private Date shippingDate;
     private String freightCompany;

    public PurchaseOrder() {
    }

	
    public PurchaseOrder(int orderNum, Product product, Customer customer) {
        this.orderNum = orderNum;
        this.product = product;
        this.customer = customer;
    }
    public PurchaseOrder(int orderNum, Product product, Customer customer, Short quantity, BigDecimal shippingCost, Date salesDate, Date shippingDate, String freightCompany) {
       this.orderNum = orderNum;
       this.product = product;
       this.customer = customer;
       this.quantity = quantity;
       this.shippingCost = shippingCost;
       this.salesDate = salesDate;
       this.shippingDate = shippingDate;
       this.freightCompany = freightCompany;
    }
   
     @Id 

    
    @Column(name="order_num", unique=true, nullable=false)
    public int getOrderNum() {
        return this.orderNum;
    }
    
    public void setOrderNum(int orderNum) {
        this.orderNum = orderNum;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    
    @Column(name="quantity")
    public Short getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Short quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="shipping_cost", precision=12)
    public BigDecimal getShippingCost() {
        return this.shippingCost;
    }
    
    public void setShippingCost(BigDecimal shippingCost) {
        this.shippingCost = shippingCost;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="sales_date", length=10)
    public Date getSalesDate() {
        return this.salesDate;
    }
    
    public void setSalesDate(Date salesDate) {
        this.salesDate = salesDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="shipping_date", length=10)
    public Date getShippingDate() {
        return this.shippingDate;
    }
    
    public void setShippingDate(Date shippingDate) {
        this.shippingDate = shippingDate;
    }

    
    @Column(name="freight_company", length=30)
    public String getFreightCompany() {
        return this.freightCompany;
    }
    
    public void setFreightCompany(String freightCompany) {
        this.freightCompany = freightCompany;
    }




}


